services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/marketsim_test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
  db:
    image: postgres:13.21-alpine3.20
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=marketsim_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - JWT_SECRET=Vm9pY2lVblNlY3JldEJlYXVjb3VwUGx1c0xvbmdFdFNlY3VyaXNlUG91ckpXVEF1dGhlbnRpZmljYXRpb25BdmVjSE1BQ1NIQTI1NkJpdHNNaW5pbXVt
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres-data: