spring:
  application:
    name: marketsim
  profiles:
    active: dev
  jpa:
    properties:
      jakarta.persistence.validation.mode: AUTO
      hibernate:
        jdbc:
          time_zone: UTC

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION:900000}
    issuer: marketsim