spring:
  application:
    name: marketsim
  profiles:
    active: test
  jpa:
    properties:
      jakarta.persistence.validation.mode: AUTO
      hibernate:
        jdbc:
          time_zone: UTC

app:
  jwt:
    secret: ${JWT_SECRET:Vm9pY2lVblNlY3JldEJlYXVjb3VwUGx1c0xvbmdFdFNlY3VyaXNlUG91ckpXVEF1dGhlbnRpZmljYXRpb25BdmVjSE1BQ1NIQTI1NkJpdHNNaW5pbXVt}
    expiration-ms: ${JWT_EXPIRATION:900000}
    issuer: marketsim